### ISSUE TITLE
flutter build apk fails while using upgrader 3.3.0

### ISSUE THREAD

**Issue by semonec** [larryaasen/upgrader#109]
When I added upgrader code, build fails, but if I remove that codes in *.dart, build works.

Ironic, it could be executed with debugging, only errors when building release apk.

my upgrader codes ls like below, put appcast xml to github public repo.

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: UpgradeAlert(
        appcastConfig: AppcastConfiguration(
          url:
              'https://raw.githubusercontent.com/**********/version/master/appcast.xml',
          supportedOS: ['android'],
        ),
        dialogStyle: Platform.isIOS
            ? UpgradeDialogStyle.cupertino
            : UpgradeDialogStyle.material,
        child: Padding(.....
.....
```

**Environment**
```
Flutter is already up to date on channel stable
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (5 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (1 available)
```
**build logs**

```
[        ] [  +26 ms] aot_android_asset_bundle: Complete
[+16101 ms] [+16013 ms] ../../third_party/dart/runtime/vm/compiler/aot/precompiler.cc: 3186: error: unreachable code
[   +1 ms] [  +31 ms] ../../third_party/dart/runtime/vm/compiler/aot/precompiler.cc: 3186: error: unreachable code
[        ] [  +57 ms] Dart snapshot generator failed with exit code -6
[  +94 ms] [  +62 ms] Dart snapshot generator failed with exit code -6
[+4600 ms] [+4575 ms] android_aot_release_android-arm: Complete
[ +101 ms] [ +152 ms] android_aot_bundle_release_android-arm: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/Users/sempark/cbeyond_flutter/.dart_tool/flutter_build/cceea1ac4ea7a35d56eef4eabe6ed057/armeabi-v7a/app.so}
[        ] [  +12 ms] android_aot_bundle_release_android-arm: Complete
[ +101 ms] [  +70 ms] Persisting file store
[        ] [  +10 ms] Done persisting file store
[        ] [  +12 ms] Target android_aot_release_android-x64 failed: Exception: AOT snapshotter exited with code -6
[        ]            #0      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:258:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:828:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:766:32)
[        ]            <asynchronous suspension>
[        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:766:32)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:595:16)
[        ]            <asynchronous suspension>
[        ]            #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:318:32)
[        ]            <asynchronous suspension>
[        ]            #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ] [  +13 ms] "flutter assemble" took 60,171ms.
[        ]            <asynchronous suspension>
[        ]            #10     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #16     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [        ] Target android_aot_release_android-arm64 failed: Exception: AOT snapshotter exited with code -6
[        ]            #0      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:258:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:828:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:766:32)
[        ]            <asynchronous suspension>
[        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:766:32)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:595:16)
[        ]            <asynchronous suspension>
[        ]            #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:318:32)
[        ]            <asynchronous suspension>
[        ]            #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #16     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[  +84 ms] [   +5 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:335:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[  +96 ms] [ +145 ms] ensureAnalyticsSent: 144ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[ +199 ms] > Task :app:compileFlutterBuildRelease FAILED
[  +53 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/sempark/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command '/Users/sempark/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1m 3s
[        ] 1 actionable task: 1 executed
[ +368 ms] Running Gradle task 'assembleRelease'... (completed in 63.8s)
[   +4 ms] "flutter apk" took 64,647ms.
[   +4 ms] Gradle task assembleRelease failed with exit code 1
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:464:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:231:5)
           <asynchronous suspension>
           #3      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:105:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

**Comment by semonec** [comment]
Found that bug is came from flutter itself, 
https://github.com/flutter/flutter/issues/83094

**Comment by larryaasen** [comment]
Looks like Flutter has a fix coming soon. Try out the next update of Flutter to see if that resolves your issue.

**Comment by tjcode19** [comment]
I was able to build release.apk I hope you've been able to resolve this issue too
