### ISSUE TITLE
Docs don't mention that you have to call initialize() before using the UpgradeAlert Widget.

### ISSUE THREAD

**Issue by Tobi696** [larryaasen/upgrader#452]
The docs don't mention that you have to call initialize() before using the UpgradeAlert Widget.

**Comment by fiki2002** [comment]
initialize as how, chief?

**Comment by dhiaCodes** [comment]
Same issue is happening with me ! 

```
Unhandled Exception: upgrader: initialize() not called. Must be called first.
E/flutter ( 5846): #0      Upgrader.verifyInit (package:upgrader/src/upgrader.dart:265:7)
E/flutter ( 5846): #1      Upgrader.appName (package:upgrader/src/upgrader.dart:271:5)
E/flutter ( 5846): #2      Upgrader.body (package:upgrader/src/upgrader.dart:277:41)
E/flutter ( 5846): #3      UpgradeAlertState.checkVersion.<anonymous closure> (package:upgrader/src/upgrade_alert.dart:149:36)
E/flutter ( 5846): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:417:42)
E/flutter ( 5846): #5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 5846): #6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 5846): #7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 5846): #8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 5846): 
```

@larryaasen please clarify if we need to call initialize() first or what ?

**Comment by penhorwood** [comment]
There must be an edge case with initialization.  I just added this package to my app.  During testing I am seeing this in the output.  If **I don't need to initialize then why am I getting this message.**

E/flutter (20841): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: upgrader: initialize() not called. Must be called first.
E/flutter (20841): #0      Upgrader.verifyInit (package:upgrader/src/upgrader.dart:262:7)
E/flutter (20841): #1      Upgrader.appName (package:upgrader/src/upgrader.dart:268:5)
E/flutter (20841): #2      Upgrader.body (package:upgrader/src/upgrader.dart:274:41)
E/flutter (20841): #3      UpgradeAlertState.checkVersion.<anonymous closure> (package:upgrader/src/upgrade_alert.dart:153:36)
E/flutter (20841): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:419:42)
E/flutter (20841): #5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (20841): #6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:423:19)
E/flutter (20841): #7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:454:5)
E/flutter (20841): #8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:12)
