### ISSUE TITLE
currentInstalledVersion is null

### ISSUE THREAD

**Issue by stevenspiel** [larryaasen/upgrader#48]
I'm getting an error with version 2.2.0 (I have to use 2.2.0 because >=2.2.1 breaks iOS with `Method not found: 'XmlDocument.parse'.`

Looks like `_installedVersion` is not getting set soon enough, because `_packageInfo.version` returns a string. You can see from the stack trace, but UpgradeAlert calls `Text(Upgrader().message())`, which calls `currentInstalledVersion()`, which is null. 

It only happens on when upgrader is show as app first loads. Hot reloading fixes the issue, but a hot restart that loads the upgrader on the first page is throwing this error. 

Tried calling `WidgetsFlutterBinding.ensureInitialized();` in case that fixes anything, but no luck.

Flutter version 1.20.1

```
flutter: [2020-08-10 17:17:39.177563 | ConsoleHandler | INFO] ---------- ERROR ----------
flutter: [2020-08-10 17:17:39.177938 | ConsoleHandler | INFO] Invalid argument(s) (replacement): Must not be null
flutter: [2020-08-10 17:17:39.178612 | ConsoleHandler | INFO]
flutter: [2020-08-10 17:17:39.179452 | ConsoleHandler | INFO] ------- STACK TRACE -------
flutter: [2020-08-10 17:17:39.180092 | ConsoleHandler | INFO] #0      _StringBase.replaceAll (dart:core-patch/string_patch.dart:637:30)
flutter: [2020-08-10 17:17:39.180469 | ConsoleHandler | INFO] #1      Upgrader.message (package:upgrader/src/upgrader.dart:251:15)
flutter: [2020-08-10 17:17:39.180754 | ConsoleHandler | INFO] #2      UpgradeCard.build.<anonymous closure> (package:upgrader/src/upgrade_alert.dart:216:43)
flutter: [2020-08-10 17:17:39.181070 | ConsoleHandler | INFO] #3      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:740:55)
flutter: [2020-08-10 17:17:39.181429 | ConsoleHandler | INFO] #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
flutter: [2020-08-10 17:17:39.181869 | ConsoleHandler | INFO] #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
flutter: [2020-08-10 17:17:39.182208 | ConsoleHandler | INFO] #6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
flutter: [2020-08-10 17:17:39.182470 | ConsoleHandler | INFO] #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: [2020-08-10 17:17:39.182786 | ConsoleHandler | INFO] #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
flutter: [2020-08-10 17:17:39.183146 | ConsoleHandler | INFO] #9      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
flutter: [2020-08-10 17:17:39.183440 | ConsoleHandler | INFO] #10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: [2020-08-10 17:17:39.183782 | ConsoleHandler | INFO] #11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: [2020-08-10 17:17:39.184135 | ConsoleHandler | INFO] #12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
flutter: [2020-08-10 17:17:39.184480 | ConsoleHandler | INFO] #13     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
flutter: [2020-08-10 17:17:39.184796 | ConsoleHandler | INFO] #14     _rootRun (dart:async/zone.dart:1190:13)
flutter: [2020-08-10 17:17:39.185188 | ConsoleHandler | INFO] #15     _CustomZone.run (dart:async/zone.dart:1093:19)
flutter: [2020-08-10 17:17:39.185543 | ConsoleHandler | INFO] #16     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
flutter: [2020-08-10 17:17:39.185855 | ConsoleHandler | INFO] #17     _invoke (dart:ui/hooks.dart:253:10)
flutter: [2020-08-10 17:17:39.186180 | ConsoleHandler | INFO] #18     _drawFrame (dart:ui/hooks.dart:211:3)
flutter: [2020-08-10 17:17:39.186911 | ConsoleHandler | INFO]
flutter: [2020-08-10 17:17:39.187507 | ConsoleHandler | INFO] ======================================================================
flutter: [2020-08-10 17:17:39.216065 | Catcher | INFO] Report result: true
```

**Comment by larryaasen** [comment]
Have you tried using version 2.5.0 of upgrader and xml 4.2.0+?

**Comment by larryaasen** [comment]
Closing this as a stale issue. If you see it now, please open a new one. Thanks.
